CREATE TABLE account(
  id SERIAL PRIMARY KEY NOT NULL,
  login CHAR(50) UNIQUE NOT NULL,
  password CHAR(50) NOT NULL
);

CREATE TABLE role(
  id SERIAL PRIMARY KEY NOT NULL,
  name CHAR(25) NOT NULL
);

CREATE TABLE feedback(
  id SERIAL PRIMARY KEY NOT NULL,
  email CHAR(50) NOT NULL
);

CREATE TABLE favorite_route(
  id SERIAL PRIMARY KEY NOT NULL,
  route_id INTEGER NOT NULL
);

CREATE TABLE my_route(
  id SERIAL PRIMARY KEY NOT NULL,
  route_id INTEGER NOT NULL
);

CREATE TABLE rating(
  id SERIAL PRIMARY KEY NOT NULL,
  route_id INTEGER NOT NULL,
  account_id INTEGER NOT NULL
);

CREATE TABLE comment(
  id SERIAL PRIMARY KEY NOT NULL,
  route_id INTEGER NOT NULL,
  account_id INTEGER NOT NULL,
  message MESSAGE_TEXT
);

CREATE TABLE neighbor(
  point_id INTEGER NOT NULL,
  neightbor_id INTEGER NOT NULL,
  distance DOUBLE NOT NULL
);

CREATE TABLE point(
  id SERIAL PRIMARY KEY NOT NULL,
  coordinates_id INTEGER NOT NULL
);

CREATE TABLE coordinates(
  id SERIAL PRIMARY KEY NOT NULL,
  lat DOUBLE NOT NULL,
  lng DOUBLE NOT NULL
);

CREATE TABLE route(
  id SERIAL PRIMARY KEY NOT NULL,
  start_point INTEGER NOT NULL,
  end_point INTEGER NOT NULL,
  distance DOUBLE NOT NULL
);

CREATE TABLE info(
  id SERIAL PRIMARY KEY NOT NULL
);

CREATE TABLE statistics(
  id SERIAL PRIMARY KEY NOT NULL,
  counter INTEGER NOT NULL,
  month_name CHAR(20)
);

CREATE TABLE schedule(
  id SERIAL PRIMARY KEY NOT NULL,
  weekday CHAR(20),
  sending_time TIME NOT NULL
);

CREATE TABLE waypoint(
  id SERIAL PRIMARY KEY NOT NULL,
  point_id INTEGER NOT NULL
);

CREATE TABLE planner(
  id SERIAL PRIMARY KEY NOT NULL,
  account_id INTEGER NOT NULL,
  route_id INTEGER NOT NULL,
  message TEXT
);