CREATE TABLE account(
  id SERIAL PRIMARY KEY NOT NULL,
  login TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE role(
  id SERIAL PRIMARY KEY NOT NULL,
  name TEXT NOT NULL
);

CREATE TABLE feedback(
  id SERIAL PRIMARY KEY NOT NULL,
  email TEXT NOT NULL
);

CREATE TABLE favorite_route(
  id SERIAL PRIMARY KEY NOT NULL,
  route_id INTEGER NOT NULL
);

CREATE TABLE my_route(
  id SERIAL PRIMARY KEY NOT NULL,
  route_id INTEGER NOT NULL
);

CREATE TABLE rating(
  id SERIAL PRIMARY KEY NOT NULL,
  value INTEGER NOT NULL
);

CREATE TABLE comment(
  id SERIAL PRIMARY KEY NOT NULL,
  message TEXT
);

CREATE TABLE neighbor(
  id SERIAL PRIMARY KEY NOT NULL,
  distance REAL NOT NULL
);

CREATE TABLE point(
  id SERIAL PRIMARY KEY NOT NULL,
  name TEXT
);

CREATE TABLE coordinates(
  id SERIAL PRIMARY KEY NOT NULL,
  lat REAL NOT NULL,
  lng REAL NOT NULL
);

CREATE TABLE route(
  id SERIAL PRIMARY KEY NOT NULL,
  distance REAL NOT NULL
);

CREATE TABLE route_info(
  id SERIAL PRIMARY KEY NOT NULL
);

CREATE TABLE statistics(
  id SERIAL PRIMARY KEY NOT NULL,
  counter INTEGER NOT NULL,
  month TEXT
);

CREATE TABLE schedule(
  id SERIAL PRIMARY KEY NOT NULL,
  day TEXT,
  time TEXT NOT NULL
);

CREATE TABLE planner(
  id SERIAL PRIMARY KEY NOT NULL,
  account_id INTEGER NOT NULL,
  datetime TEXT NOT NULL,
  message TEXT
);