CREATE TABLE account(
  id SERIAL PRIMARY KEY NOT NULL,
  login CHAR(50) UNIQUE NOT NULL,
  password CHAR(50) NOT NULL
);

CREATE TABLE role(
  id SERIAL PRIMARY KEY NOT NULL,
  name CHAR(25) NOT NULL
);

CREATE TABLE feedback(
  id SERIAL PRIMARY KEY NOT NULL,
  email CHAR(50) NOT NULL
);

CREATE TABLE favorite_route(
  id SERIAL PRIMARY KEY NOT NULL,
  route_id INTEGER NOT NULL
);

CREATE TABLE my_route(
  id SERIAL PRIMARY KEY NOT NULL,
  route_id INTEGER NOT NULL
);

CREATE TABLE rating(
  id SERIAL PRIMARY KEY NOT NULL,
  value INTEGER NOT NULL
);

CREATE TABLE comment(
  id SERIAL PRIMARY KEY NOT NULL,
  message TEXT
);

CREATE TABLE neighbor(
  id SERIAL PRIMARY KEY NOT NULL,
  distance REAL NOT NULL
);

CREATE TABLE point(
  id SERIAL PRIMARY KEY NOT NULL,
  name TEXT
);

CREATE TABLE coordinates(
  id SERIAL PRIMARY KEY NOT NULL,
  lat REAL NOT NULL,
  lng REAL NOT NULL
);

CREATE TABLE route(
  id SERIAL PRIMARY KEY NOT NULL,
  distance REAL NOT NULL
);

CREATE TABLE route_info(
  id SERIAL PRIMARY KEY NOT NULL
);

CREATE TABLE statistics(
  id SERIAL PRIMARY KEY NOT NULL,
  counter INTEGER NOT NULL,
  month CHAR(20)
);

CREATE TABLE schedule(
  id SERIAL PRIMARY KEY NOT NULL,
  day CHAR(20),
  time CHAR(20) NOT NULL
);

CREATE TABLE planner(
  id SERIAL PRIMARY KEY NOT NULL,
  account_id INTEGER NOT NULL,
  datetime CHAR(20) NOT NULL,
  message TEXT
);